version: "3.4"

volumes: 
  mongo:

services:
  db:
    container_name: mongo
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes: 
      - mongo:/data/db

  api:
    depends_on: 
      - db
    image: "edu/api"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3001:3000
    volumes:
      - ./:/api
